<?php
/* Copyright (c) 2010 Leifos, GPL, see docs/LICENSE */

include_once("./Services/Table/classes/class.ilTable2GUI.php");

/**
 * Workspace access handler table GUI class
 *
 * @author Jörg Lützenkirchen <luetzenkirchen@leifos.de>
 * @version $Id: class.adnCountryTableGUI.php 27876 2011-02-25 16:51:38Z jluetzen $
 *
 * @ingroup ServicesPersonalWorkspace
 */
class ilWorkspaceAccessTableGUI extends ilTable2GUI
{
	protected $node_id; // [int]
	protected $handler; // [ilWorkspaceAccessHandler]

	/**
	 * Constructor
	 *
	 * @param object $a_parent_obj parent gui object
	 * @param string $a_parent_cmd parent default command
	 * @param int $a_node_id current workspace object
	 * @param object $a_handler workspace access handler
	 */
	function __construct($a_parent_obj, $a_parent_cmd, $a_node_id, $a_handler)
	{
		global $ilCtrl, $lng;

		$this->node_id = $a_node_id;
		$this->handler = $a_handler;

		parent::__construct($a_parent_obj, $a_parent_cmd);

		$this->setId("il_tbl_wsacl");

		$this->setTitle($lng->txt("wsp_shared_table_title"));
				
		$this->addColumn($this->lng->txt("wsp_shared_with"), "title");
		$this->addColumn($this->lng->txt("details"), "type");
		$this->addColumn($this->lng->txt("actions"));
		
		$this->setDefaultOrderField("title");
		$this->setDefaultOrderDirection("asc");

		$this->setFormAction($ilCtrl->getFormAction($a_parent_obj));
		$this->setRowTemplate("tpl.access_row.html", "Services/PersonalWorkspace");
		// uzk-patch: begin
		$this->initFilter();
		// uzk-patch: end
		$this->importData();
	}

	/**
	 * Import data from DB
	 */
	protected function importData()
	{
		include_once("./Services/User/classes/class.ilUserUtil.php");
		
		$data = array();
		foreach($this->handler->getPermissions($this->node_id) as $obj_id)
		{				
			// title is needed for proper sorting
			// special modes should always be on top!
			$title = null;
			
			switch($obj_id)
			{
				case ilWorkspaceAccessGUI::PERMISSION_REGISTERED:
					$caption = $this->lng->txt("wsp_set_permission_registered");
					$title = "0".$caption;
					break;
				
				case ilWorkspaceAccessGUI::PERMISSION_ALL_PASSWORD:
					$caption = $this->lng->txt("wsp_set_permission_all_password");
					$title = "0".$caption;
					break;
				
				case ilWorkspaceAccessGUI::PERMISSION_ALL:
					$caption = $this->lng->txt("wsp_set_permission_all");
					$title = "0".$caption;
					break;	
												
				default:
					$type = ilObject::_lookupType($obj_id);					
					$type_txt = $this->lng->txt("obj_".$type);	
					
					if($type === null)
					{					
						// invalid object/user
					}
					else if($type != "usr")
					{					
						$title = $caption = ilObject::_lookupTitle($obj_id);											
					}
					else
					{						
						$caption = ilUserUtil::getNamePresentation($obj_id, false, true); 
						$title = strip_tags($caption);
					}
					break;
			}
			
			if($title)
			{
				// uzk-patch: begin    
				$search_string = $this->filter['search_string'];
				$search_types = array();
				
				$this->filter['usr'] ? $search_types['usr'] = 'usr' : NULL;
				$this->filter['crs'] ? $search_types['crs'] = 'crs' : NULL;
				$this->filter['grp'] ? $search_types['grp'] = 'grp' : NULL;
				
				if(strlen(stristr($title, $search_string))|| $search_string == false)
				{
					if(count($search_types)  == 0 || count($search_types) > 0 && in_array($type, $search_types))
					{
						$data[] = array("id"      => $obj_id,
						                "title"   => $title,
						                "caption" => $caption,
						                "type"    => $type_txt);
					}
				}
				// uzk-patch: end
			}
		}
	
		$this->setData($data);
	}
	
	/**
	 * Fill table row
	 *
	 * @param array $a_set data array
	 */
	protected function fillRow($a_set)
	{
		global $ilCtrl;
		
		// properties
		$this->tpl->setVariable("TITLE", $a_set["caption"]);
		$this->tpl->setVariable("TYPE", $a_set["type"]);		

		$ilCtrl->setParameter($this->parent_obj, "obj_id", $a_set["id"]);
		$this->tpl->setVariable("HREF_CMD",
			$ilCtrl->getLinkTarget($this->parent_obj, "removePermission"));
		$this->tpl->setVariable("TXT_CMD", $this->lng->txt("remove"));
	}
	
	
// uzk-patch: begin	
	function initFilter()
	{
		global $lng, $ilCtrl;
		//		parent::initFilter(); // TODO: Change the autogenerated stub
		
		include_once("./Services/Form/classes/class.ilTextInputGUI.php");
		$search = new ilTextInputGUI($lng->txt("search"), "search_string");
		$search->setSize(20);
		$search->setSubmitFormOnEnter(true);
		$this->addFilterItem($search);
		$search->readFromSession();
		$this->filter["search_string"] = $search->getValue();
		
		include_once("./Services/Form/classes/class.ilCheckboxGroupInputGUI.php");
		include_once("./Services/Form/classes/class.ilCheckboxInputGUI.php");
		
		$object_types = new ilCheckboxGroupInputGUI($lng->txt('obj_type'), 'search_types');
		
		$cb_usr = new ilCheckboxInputGUI($lng->txt('user'), 'search_types["usr"]');
		$cb_usr->setValue('usr');
		
		$cb_crs = new ilCheckboxInputGUI($lng->txt('crs'), 'search_types["crs"]');
		$cb_crs->setValue('crs');
		
		$cb_grp = new ilCheckboxInputGUI($lng->txt('grp'), 'search_types["grp"]');
		$cb_grp->setValue('grp');
		
		$object_types->addOption($cb_usr);
		$object_types->addOption($cb_crs);
		$object_types->addOption($cb_grp);
		
		$object_types->setValue($_SESSION['shop_advanced_search']['details']);
		
		$this->addFilterItem($object_types);
		$object_types->readFromSession();
	}
	// uzk-patch: end	
}

?>