[MAIN]

ILIAS_MASTER_CLIENT_ID = "<MASTER_CLIENT_ID>"
ILIAS_BASE_PATH = "/<PATH>/<TO>/<ILIAS_ROOT_DIR>"
ILIAS_EXTERN_DATA = "/<PATH>/<TO>/<ILIAS_EXTERNAL_DATA_DIR>"
MYSQL_ADMIN_USER = "<DB_ADMIN_USER>"
MYSQL_ADMIN_PASS = "<DB_ADMIN_PASS>"

[CLIENT_1]

CLIENT_ID = "<SLAVE_1_CLIENT_ID>"
CLIENT_NAME = "<SLAVE_1_CLIENT_NAME>"
CLIENT_DESCRIPTION = "<SLAVE_1_CLIENT_DESCRIPTION>"
MYSQL_SERVER = "<SLAVE_1_DB_HOST>"
MYSQL_DB_NAME = "<SLAVE_1_DB_NAME>"
MYSQL_USER = "<SLAVE_1_DB_USER>"
MYSQL_PASS = "<SLAVE_1_DB_PASS>"

[CLIENT_2]

CLIENT_ID = "<SLAVE_2_CLIENT_ID>"
CLIENT_NAME = "<SLAVE_2_CLIENT_NAME>"
CLIENT_DESCRIPTION = "<SLAVE_2_CLIENT_DESCRIPTION>"
MYSQL_SERVER = "<SLAVE_2_DB_HOST>"
MYSQL_DB_NAME = "<SLAVE_2_DB_NAME>"
MYSQL_USER = "<SLAVE_2_DB_USER>"
MYSQL_PASS = "<SLAVE_2_DB_PASS>"
