<?php
include_once './Services/Calendar/interfaces/interface.ilCalendarAppointmentPresentation.php';
include_once './Services/Calendar/classes/AppointmentPresentation/class.ilAppointmentPresentationGUI.php';

/**
 *
 * @author Jesús López Reyes <lopez@leifos.com>
 * @version $Id$
 *
 * @ilCtrl_IsCalledBy ilAppointmentPresentationSessionGUI: ilCalendarAppointmentPresentationGUI
 *
 * @ingroup ServicesCalendar
 */
class ilAppointmentPresentationSessionGUI extends ilAppointmentPresentationGUI implements ilCalendarAppointmentPresentation
{

	public function getHTML()
	{
		global $lng, $ilCtrl;

		$a_infoscreen = $this->getInfoScreen();
		$a_app = $this->appointment;

		//include_once('./Services/Calendar/classes/class.ilCalendarCategoryAssignments.php');
		include_once "./Modules/Session/classes/class.ilObjSession.php";

		$cat_id = $this->getCatId($a_app['event']->getEntryId());
		$cat_info = $this->getCatInfo($cat_id);

		//ilLoggerFactory::getRootLogger()->debug("cat_info",$cat_info);

		$obj = new ilObjSession($cat_info['obj_id'],false);

		$description_text = $cat_info['title'] . ", " . ilObject::_lookupDescription($cat_info['obj_id']);
		$a_infoscreen->addSection($cat_info['title']);

		if ($a_app['event']->getDescription()) {
			$a_infoscreen->addProperty($lng->txt("description"), ilUtil::makeClickable(nl2br($a_app['event']->getDescription())));
		}
		$a_infoscreen->addProperty($lng->txt(ilObject::_lookupType($cat_info['obj_id'])), $description_text);

		$a_infoscreen->addSection($lng->txt((ilOBject::_lookupType($cat_info['obj_id']) == "usr" ? "app" : ilOBject::_lookupType($cat_info['obj_id'])) . "_info"));


		//TODO FIX THIS, DOES NOT SHOW THE LOCATION
		//$a_infoscreen->addProperty($lng->txt("cal_location"),ilUtil::makeClickable($a_app['event']->getLocation()));
		if($a_app['event']->getLocation())
		{
			$a_infoscreen->addProperty($lng->txt("cal_location"),ilUtil::makeClickable($a_app['event']->getLocation()));
		}
		//TODO get the details/workflow, information about lecturer, Files.

		return $a_infoscreen;
	}

	public function addToolbar(ilToolbarGUI $a_toolbar)
	{
		parent::addToolbar($a_toolbar); // TODO: Change the autogenerated stub
	}
}