<?php
include_once './Services/Calendar/interfaces/interface.ilCalendarAppointmentPresentation.php';
include_once './Services/Calendar/classes/AppointmentPresentation/class.ilAppointmentPresentationGUI.php';

/**
 *
 * @author Jesús López Reyes <lopez@leifos.com>
 * @version $Id$
 *
 *
 * @ingroup ServicesCalendar
 */
class ilAppointmentPresentationBookingPoolGUI extends ilAppointmentPresentationGUI implements ilCalendarAppointmentPresentation
{
	/**
	 * Get singleton
	 *
	 * @return self
	 */
	public static function getInstance()
	{
		if (self::$instance === null || !(self::$instance instanceof ilAppointmentPresentationBookingPoolGUI)) {
			self::$instance = new self;
		}

		return self::$instance;
	}

	public function addInfoScreen(ilInfoScreenGUI $a_infoscreen, $a_app)
	{
		global $lng;

		//include_once('./Services/Calendar/classes/class.ilCalendarCategoryAssignments.php');
		include_once "./Modules/Course/classes/class.ilObjBookingPool.php";

		$cat_id = $this->getCatId($a_app['event']->getEntryId());
		$cat_info = $this->getCatInfo($cat_id);

		//ilLoggerFactory::getRootLogger()->debug("cat_info",$cat_info);

		$bp = new ilObjBookingPool($cat_info['obj_id'],false);

		$description_text = $cat_info['title'] . ", " . ilObject::_lookupDescription($cat_info['obj_id']);
		$a_infoscreen->addSection($cat_info['title']);

		if ($a_app['event']->getDescription()) {
			$a_infoscreen->addProperty($lng->txt("description"), ilUtil::makeClickable(nl2br($a_app['event']->getDescription())));
		}
		$a_infoscreen->addProperty($lng->txt(ilObject::_lookupType($cat_info['obj_id'])), $description_text);

		$a_infoscreen->addSection($lng->txt((ilOBject::_lookupType($cat_info['obj_id']) == "usr" ? "app" : ilOBject::_lookupType($cat_info['obj_id'])) . "_info"));

		//TODO ADDITIONAL INFORMATION + POST BOOKING INFORMATION
		//$a_infoscreen->addProperty($lng->txt("crs_important_info"), $bp->getImportantInformation());

		return $a_infoscreen;
	}

	public function addToolbar(ilToolbarGUI $a_toolbar)
	{
		parent::addToolbar($a_toolbar); // TODO: Change the autogenerated stub
	}
}