<?php
include_once './Services/Calendar/classes/class.ilCalendarSettings.php';

/**
 * Class ilCalendarAppointmentPresentationGUI
 *
 * @author	Jesús López <lopez@leifos.com>
 * @version  $Id$
 * @ilCtrl_IsCalledBy ilCalendarAppointmentPresentationGUI: ilColumnGUI
 * @ilCtrl_Calls ilCalendarAppointmentPresentationGUI: ilInfoScreenGUI, ilCalendarAppointmentGUI
*/

class ilCalendarAppointmentPresentationGUI
{
	protected $seed = null;
	protected static $instance = null;
	protected $settings = null;


	/**
	 * Singleton
	 *
	 * @access public
	 * @param
	 * @return
	 */
	protected function __construct(ilDate $seed = null)
	{
		global $DIC;
		$this->lng = $DIC->language();
		$this->ctrl = $DIC->ctrl();

		$this->settings = ilCalendarSettings::_getInstance();

		$this->seed = $seed;
	}

	/**
	 * get singleton instance
	 *
	 * @access public
	 * @param
	 * @return
	 * @static
	 */
	public static function _getInstance(ilDate $seed)
	{
		if(isset(self::$instance) and self::$instance)
		{
			return self::$instance;
		}
		return self::$instance = new ilCalendarAppointmentPresentationGUI($seed);
	}

	/**
	 * Get seed date
	 */
	public function getSeed()
	{
		return $this->seed;
	}

	public function show($a_app)
	{
		global $tpl;

		include_once "./Services/Calendar/classes/AppointmentPresentation/class.ilAppointmentPresentationFactory.php";

		$tpl = new ilTemplate('tpl.appointment_presentation.html',true,true,'Services/Calendar');

		$f = ilAppointmentPresentationFactory::getPresentation($a_app);

		ilLoggerFactory::getRootLogger()->debug("clase de la factory:".get_class($f));

		//pending show the HTML
		$toolbar = $this->fillToolbar($a_app);
		if($toolbar)
		{
			$f->addToolbar($toolbar);
			$tpl->setCurrentBlock("toolbar");
			$tpl->setVariable("TOOLBAR",$f->getToolbar()->getHTML());
			$tpl->parseCurrentBlock();
		}

		$cat_info = $this->getCatInfo($a_app);

		//we can move this to the factory.
		if($cat_info['editable'] and !$a_app['event']->isAutoGenerated())
		{
			ilLoggerFactory::getRootLogger()->debug("event get entry".$a_app['event']->getEntryId());
			$tpl->setCurrentBlock('panel_edit_link');
			$tpl->setVariable('TXT_PANEL_EDIT',$this->lng->txt('edit'));

			$this->ctrl->clearParametersByClass('ilcalendarappointmentgui');
			$this->ctrl->setParameterByClass('ilcalendarappointmentgui','seed',$this->getSeed()->get(IL_CAL_DATE));
			$this->ctrl->setParameterByClass('ilcalendarappointmentgui','app_id',$a_app['event']->getEntryId());
			$this->ctrl->setParameterByClass('ilcalendarappointmentgui','dt',$a_app['dstart']);
			$tpl->setVariable('PANEL_EDIT_HREF',$this->ctrl->getLinkTargetByClass('ilcalendarappointmentgui','askEdit'));

			$tpl->setCurrentBlock('panel_delete_link');
			$tpl->setVariable('TXT_PANEL_DELETE',$this->lng->txt('delete'));

			$this->ctrl->clearParametersByClass('ilcalendarappointmentgui');
			$this->ctrl->setParameterByClass('ilcalendarappointmentgui','seed',$this->getSeed()->get(IL_CAL_DATE));
			$this->ctrl->setParameterByClass('ilcalendarappointmentgui','app_id',$a_app['event']->getEntryId());
			$this->ctrl->setParameterByClass('ilcalendarappointmentgui','dt',$a_app['dstart']);
			$tpl->setVariable('PANEL_DELETE_HREF',$this->ctrl->getLinkTargetByClass('ilcalendarappointmentgui','askdelete'));
			$tpl->parseCurrentBlock();
		}

		$info_screen = $this->setInfoScreen($a_app);
		$tpl->setVariable("CONTENT",$f->addInfoScreen($info_screen, $a_app)->getHTML());

		return $tpl->get();
	}

	public function fillToolbar()
	{
		global $DIC;

		$toolbar = $DIC->toolbar();
		//$toolbar->setHidden(true);

		return $toolbar;
	}

	//TODO remove this stuff from here.
	protected function getCatInfo($a_app)
	{
		include_once('./Services/Calendar/classes/class.ilCalendarCategoryAssignments.php');

		$cat_id = ilCalendarCategoryAssignments::_lookupCategory($a_app['event']->getEntryId());
		$cat_info = ilCalendarCategories::_getInstance()->getCategoryInfo($cat_id);
		$entry_obj_id = isset($cat_info['subitem_obj_ids'][$cat_id]) ?
			$cat_info['subitem_obj_ids'][$cat_id] :
			$cat_info['obj_id'];

		return $cat_info;

	}


	/**
	 * @param $a_app
	 * @return ilInfoScreenGUI
	 */
	public function setInfoScreen($a_app)
	{
		include_once("./Services/InfoScreen/classes/class.ilInfoScreenGUI.php");

		$infoscreen = new ilInfoScreenGUI($this);
		$infoscreen->setFormAction($this->ctrl->getFormAction($this));

		return $infoscreen;

	}
}